project:
  type: website
  output-dir: docs
  resources: 
    - ads.txt

website:
  page-navigation: true
  title: "Kaizhong (Mike) Mu"
  favicon: "/_assets/images/favicon.ico"
  open-graph: true
  bread-crumbs: true
  back-to-top-navigation: true
  site-url: "https://kaizhongmu.github.io/" 
  twitter-card: true
  navbar:
    tools-collapse: true
    pinned: true
    logo: "/_assets/images/brown-logo.png"
    logo-alt: "Brown University"
    logo-href: index.qmd
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: ProjectsAndApps.qmd
        text: Projects & Apps
      - href: CourseAndAward.qmd
        text: Course
      - href: Life.qmd
        text: Life
      - href: cv.qmd
        text: CV
      - icon: linkedin
        href: https://www.linkedin.com/in/mikemu123/
        target: _blank
      - icon: github
        href: "https://github.com/Kaizhongmu"
        target: _blank
      
      
      
  page-footer: 
    background: "#4A90E2"
    left: "Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    center:
      - text: "Copyright 2025 @ Kaizhong (Mike) Mu"
      - text: "License"
        href: license.txt
    right: 
      - icon: twitter 
        href: https://twitter.com/rafiqr35 
        target: _blank
      - icon: youtube
        href: https://youtube.com/@quanttube
        target: _blank
      - icon: envelope
        href: mailto:Kaizhong_mu@brown.edu?subject&body
        target: _blank
      

    border: true
  reader-mode: true


filters:
  - quarto-version.lua
  
format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 400px
      body-width: 1680px
    code-copy: true
    code-overflow: scroll
    mainfont: lualatex
    code-line-numbers: false
    highlight-style: ayu-dark
    code-tools: true
    code-fold: false
    code-block-bg: false
    code-block-border-left: true
    minimal: false
    anchor-sections: true
    smooth-scroll: true
    toc-location: left
    
    



