---
title: Life
excerpt: My Life and Interests
date: 2025-10-14
published-title: Life last updated
---

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>

## Life

### Road Trip: Solo Cross-Country Road Trip (2023)

After graduating with my bachelor's degree, I embarked on a solo journey across the United States from the West Coast to the East Coast. I traversed 19 states, winding through the Sierra Nevada mountains, rolling past Texas oil fields, and enjoying sun-kissed beaches of Florida. On one remarkable day, I experienced the changing of all four seasons.

### Sailing: Last Sailing in San Diego (2022)

I love sailing—thriving in the exhilaration of sudden storms at sea, yet equally cherishing the quiet moments on calm waters, reflecting on life. And sailing is a team sport, built on trust and coordination, where every crew member matters—this is also why I like it.

### Cycling: UCST Founder (2019)

I once cycled with my friend all the way from Tianjin to Beijing, China, embracing the challenge and freedom of the journey. Believing that cycling should not be limited to those who can afford expensive equipment, I co-founded the Tianjin United Cycling Club (UCST) in high school, bringing together students from 13 schools to share and experience the joy of cycling.
