---
listing: 
  - id: phdrs
    contents: "/research/"
    type: grid
    grid-columns: 2
    grid-item-align: center
    image-lazy-loading: true
    fields: [title, image, author,date]
    sort: "date desc"
---  

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6878992848042528"
     crossorigin="anonymous"></script>  

## Research Interests   

::: {#phdrs}
:::

## Publications & Manuscripts

### A Reliable Change Estimation Method for Severely Cognitively Impaired Populations
**Authors:** Mu, K., Zhang, D., & Eloyan, A.  
**Status:** Manuscript in preparation for submission to Alzheimer's & Dementia  
**Role:** First and corresponding author; draft completed July 2025, currently undergoing formatting.

### Longitudinal miRNA Profiles in Breast Cancer Tissue and Plasma: Associations with Hormone Receptors, Response, and Survival
**Authors:** Ryspayeva, D., Seyhan, A. A., Mu, K., Liu, M., Purcell, C., MacDonald, W. J., Halytskiy, V., Drevytska, T., Inomistova, M., Khranovska, N., Potorocha, O., Taran, L., Sumkina, O., Smolanka, I. Sr., & El-Deiry, W. S.  
**Journal:** World Journal of Clinical Oncology  
**Status:** Manuscript submitted October 2025 (Manuscript No. 115287)  
**Role:** Third author.

## Current & Past Research 

### An Bayesian-based RNN Method for MNAR/MAR + left-censored longitudinal
**Advisor:** Dr. Ani Eloyan  
**Duration:** 09/25 – Present

- This thesis extends prior SRB-based work by replacing its predefined linear trend and single-retest constraint with an RNN architecture to fully utilize multiple follow-ups while preserving Bayesian uncertainty quantification.
- Constructed a unified likelihood that simultaneously handles MNAR/MAR missingness and left-censoring in Alzheimer's longitudinal data through RNN hidden states that capture temporal dependence.
- Implemented Bayesian inference, specifically variational inference, enabling the RNN to inherently model incomplete data while maintaining uncertainty quantification and computational efficiency.
- Basic derivations completed, with manuscript preparation in progress; to be presented as a poster at Brown in April 2026

### A Bayesian Cognitive Change Method for Censored Longitudinal Data
**Advisor:** Dr. Ani Eloyan  
**Duration:** 01/25 – 07/25

- Designed simulation study and an R Shiny App to show that SRB method underestimates cognitive change in Severe dementia whose follow-ups are left-censored at floor of NACC test battery in Longitudinal EOAD Study (LEADs)
- Extended the SRB method by introducing Bayesian Inference that models censored follow-ups as random variables under a censored (Tobit-type) likelihood, realized through the MCMC (Hastings-Metropolis) implemented in R Stan.
- Conducted simulation and real-data analyses demonstrating the proposed method reduce the underestimation while preserving the interpretability aspect of the SRB index and providing credible intervals for uncertainty quantification.
- Resulted in a manuscript under formatting and presentations at three conferences.

### Nonlinear Mixed Effect Model for Alzheimer's Disease Biomarker
**Advisor:** Dr. Ani Eloyan  
**Duration:** 09/24 – 12/24

- Conducted literature reviews on vivo Alzheimer's disease imaging biomarker (tau-PET, WMH in MRI) and Spline modeling techniques (B-spline, Natural-spline, penalized-spline)
- Constructed a P-spline design matrix based on cubic B-spline basis function within mixed-effects framework to model the nonlinear increment of White Matter Hyperintensities (WMH) volume in longitudinal MRI data.

### Translational Medical Research Collaboration
**Collaborator:** Dr. Dinara Ryspayeva, Dr. Attila Seyhan, Dr. Wafik El-Deiry. Legorreta Cancer Center  
**Duration:** 03/25 – 09/25

- Led and conducted a full pipeline of statistical analyses for breast cancer miRNA biomarker discovery —including missing data imputation, survival data collection guidance, survival analysis.
- Identified MAR assumption via sensitivity analyses and applied conditional mean imputation for missing data
- Built Cox regression model to evaluate the predictive associations of miR-34a, miR-137, miR-373, miR-124a, and miR-155 with overall survival, taking account for both biological interpretability (up/down regulation, interactions) and statistical rigor (PH assumption, multicollinearity, influential point).
- Resulted in a manuscript currently under submission to "World Journal of Clinical Oncology"

### Health Data Science Summer Fellowship Program
**Advisor:** Dr. Alyssa Bilinski  
**Duration:** 06/25 – 08/25

- Received training in data tidying in R, visualization in Tableau, data management in SQL, and causal inference.
- Applied Large Language Model (LLMs) (OpenAI) for free-text classification of public response to private equity, aiming to evaluate and improve prompt effectiveness in domain-specific text understanding.
- Built an automated evaluation pipeline and interactive Shiny App to benchmark AI annotations against human ground truth.
- Resulted in oral presentation to program faculty and fellows at the final symposium.

### Comparative Analysis of Machine Learning Models for Unemployment Prediction
**Advisor:** Dr. Colin Cameron  
**Duration:** 12/22 – 03/23

- Collected and managed unemployment related data through APIs, web scraping (BeautifulSoup) in Python
- Implemented and Compared multiple regression models, including OLS, LASSO, and a novel dimension-reduced local weighted regression applying PCA, for unemployment rate prediction.
- Evaluated and visualized model results in Stata and RStudio, using key metrics like Mean Squared Error (MSE), Mean Absolute Deviation (MAD), and R-squared, accuracy, and efficiency.

### Graph-Based Change-Point Detection Method for High-Dimensional Network Data
**Advisor:** Dr. Hao Chen, Assoc. Prof. of Statistics, UCD  
**Duration:** 09/22 – 01/23

- Conducted literature reviews on graph theory and graph models (Stochastic Block Models, Erdős–Rényi graphs and Configuration Model)
- Refined gSeg R-package, implementing a combination of Image Analysis and SCAN statistics test in detecting change-point in dynamic social networks, while optimizing the algorithms for computational efficiency and scalability
- Designed and conducted simulation studies in R to evaluate the predictive performance of the proposed method against conventional approaches, across different levels of graph sparsity, edge density, and network connectivity

## Presentations and Conferences

| Date | Conference | Talk & Award |
|------|------------|--------------|
| Jun 9-11, 2025 | Southern Regional Council On Statistics (SRCOS) | Poster presentation & Boyd Harshburger Travel Award Winner |
| Aug 14-16, 2025 | Statistics in Pharmaceuticals (SIP) | Poster presentation |
| Oct 10, 2025 | ASA NJ Statistics Workshop 2025 | Poster presentation |
